name: 'Flutter FVM config action'
description: 'An action that parses an https://github.com/leoafarias/fvm config file into environment variables which can then be used to configure the https://github.com/subosito/flutter-action.'
inputs:
  path:
    description: 'Path to the FVM config file'
    required: false
    default: '.fvm/fvm_config.json'
runs:
  using: 'node12'
  main: 'index.js'